replicaCount: 1

wordpressUser: admin
wordpressPW: admin123
wordpressEmail: admin@example.com
wordpressFirstName: Admin
wordpressLastName: User
wordpressBlogName: "My WordPress"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

persistence:
  size: 1Gi

mysql:
  enabled: true
  auth:
    username: wpuser
    password: wppassword
    database: wordpress
  image:
    tag: "8.0"
  service:
    ports:
      mysql: "3306"

database:
  host: mysql
  port: 3306
  name: wordpress
  user: wpuser
  password: wppassword

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 0.1
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: mywordpress.i01-8.m3-dev.services
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mywordpress-tls
      hosts:
        - mywordpress.i01-8.m3-dev.services
