apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "waiting for db"

              until nc -z {{ .Values.database.host }} {{ .Values.database.port }}; do
                echo "MySQL is unavailable - sleeping"
                sleep 2
              done
              
              echo "MySQL is ready"
        - name: wordpress-plugin-installer
          image: wordpress:6.4-apache
          command:
            - bash
            - -c
            - |
              echo "Checking plugin installation"
              
              mkdir -p /var/www/html/wp-content/plugins
              
              # proof if akismet is installed
              if [ -d "/var/www/html/wp-content/plugins/akismet" ]; then
                echo "Akismet plugin already exists, skipping installation"
                exit 0
              fi

              apt update && apt install -y unzip
              
              echo "Download Akismet"
              cd /tmp
              curl -L -o akismet.zip https://downloads.wordpress.org/plugin/akismet.5.3.1.zip
              
              # Extract akismet
              echo "Extracting plugin"
              unzip -q akismet.zip -d /var/www/html/wp-content/plugins/
              
              echo "Akismet successfully installed"
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      containers:
        - name: wordpress
          image: wordpress:6.4-apache
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
              name: http
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.database.host }}:{{ .Values.database.port }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.database.user | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: WORDPRESS_ADMIN_USER
              value: {{ .Values.wordpressUser | quote }}
            - name: WORDPRESS_ADMIN_PASSWORD
              value: {{ .Values.wordpressPW | quote }}
            - name: WORDPRESS_ADMIN_EMAIL
              value: {{ .Values.wordpressEmail | quote }}
            - name: WORDPRESS_TITLE
              value: {{ .Values.wordpressBlogName | quote }}
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      tolerations:
        - key: "m3.services/workernode"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}