apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.4-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-postgresql:5432
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: WORDPRESS_ADMIN_USER
              value: {{ .Values.wordpressUser | quote }}
            - name: WORDPRESS_ADMIN_PASSWORD
              value: {{ .Values.wordpressPW | quote }}
            - name: WORDPRESS_ADMIN_EMAIL
              value: {{ .Values.wordpressEmail | quote }}
            - name: WORDPRESS_TITLE
              value: {{ .Values.wordpressBlogName | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.request.cpu | quote }}
              memory: {{ .Values.resources.request.memory | quote }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress-pvc